name: SignSystem
version: ${sign.version}
main: eu.cloudnetservice.sign.plugin.ProjectMain

depend: [CloudNetAPI]

website: https://cloudnetservice.eu/
description: CloudNet Sign Interface for the Central server

author: CloudNetService


commands:
  signs:

